# Generated by Django 5.0.3 on 2024-03-27 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "کامنت", "verbose_name_plural": "کامنت ها"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "پیام", "verbose_name_plural": "پیام ها"},
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(verbose_name="متن"),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(to="blog.category", verbose_name="دسته بندی"),
        ),
        migrations.AlterField(
            model_name="article",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="ساخته شده در"),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to="image/articles", verbose_name="عکس"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="اسلاگ"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=100, verbose_name="موضوع"),
        ),
        migrations.AlterField(
            model_name="article",
            name="update",
            field=models.DateTimeField(auto_now=True, verbose_name="بروز رسانی"),
        ),
        migrations.AlterField(
            model_name="category",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="ساخته شده در"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=200, verbose_name="موضوع"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.article",
                verbose_name="مقاله",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(verbose_name="متن وبلاگ"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="ساخته شده در"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="blog.comment",
                verbose_name="کامنت",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="ساخته شده در"),
        ),
        migrations.AlterField(
            model_name="message",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(verbose_name="متن"),
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(max_length=100, verbose_name="موضوع"),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.article"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
